org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.overridePathCheck=true
ksp.useKSP2=false
kotlin.incremental=false
android.builtInKotlin=false
android.newDsl=false
